### ISSUE TITLE
Cannot connect to mariadb

### ISSUE THREAD

**Issue by delanym** [Plopix/docker-mysqlproxyprofiler#5]
With a docker compose file
```
services:
  dbproxy:
    image: plopix/docker-mysqlproxyprofiler
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 10.1.0.110:3306:3306
    environment:
      BACKEND: mariadb:3306

  mariadb:
    image: mariadb:11.5.2
...
```
I cannot connect DBeaver to the proxy/db
> Could not connect to 10.1.0.110:3306 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
